name: govt_departments_and_agencies
description: "Directory of U.S. Government Departments and Agencies"
publish_to: "none"

version: 3.0.0+15

environment:
  sdk: ^3.6.0
dependencies:
  app_tracking_transparency: ^2.0.0
  package_info_plus: ^9.0.0
  change_app_package_name: ^1.0.0
  google_mobile_ads: ^6.0.0
  http: ^1.0.0
  shared_preferences: ^2.2.2
  cloud_firestore: '>=5.5.0'
  firebase_core: ^4.1.1
  firebase_auth: '>=5.3.3'
  url_launcher: ^6.3.0
  path_provider: ^2.0.0
  provider: ^6.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  remove_alpha_ios: true
